version: '3.8'

services:
  app:
    build: ../
    entrypoint: .docker/entrypoint.sh
    container_name: e-commerce
    ports:
      - 3000:3000
    volumes:
      - ../:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - 'db'

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=b2rise
    ports:
      - '5432:5432'
    volumes:
      - ./pg_data:/var/lib/postgresql
    networks:
      - app-network

  pgAdmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@gmail.com'
      PGADMIN_DEFAULT_PASSWORD: 'admin'
    ports:
      - '16543:80'
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
